name: xtensor-benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::benchmark
  - conda-forge::libblitz
  - eigen
  - armadillo
  - xsimd
  - xtensor
  - xtl
  - cmake
  - gmp
  - numpy
  - python
  - pip:
    - pythran
