name: xtensor-benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::benchmark
  - conda-forge::libblitz
  - conda-forge::pythran
  - eigen
  - armadillo
  - xsimd
  - xtensor
  - xtl
  - cmake
  - gmp
  - numpy
  - python==3.7
