name: xtensor-benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::benchmark
  - conda-forge::libblitz
  - conda-forge::pythran
  - eigen>=3.0
  - armadillo
  - xsimd
  - xtensor
  - xtl
  - cmake>=3.1
  - gmp
  - numpy
  - python>=3.0
